Pull Request for the project Positioning and Floating Elements
jose-Abel/New_York_Times_Article_Clone pull request #7
Opened 2020-07-17 21:04 UTC by jose-Abel

Hello,

This is the code review request for the 3rd project on HTML and CSS section of the Microverse curriculum "Positioning and Floating Elements", hoping to get amazing feedback!

Happy coding!

2020-07-17 22:40 UTC, krys2fa requested changes
### Good job on the project @jose-Abel and @danielufeli 👏 
You made good use of semantic HTML and utilized CSS best practices 🖖  

### Status: Changes Required ♻️ 
Kindly work on the following issues to get this project approved. Don't forget to request a code review after implementing the changes.

- [x] [MANDATORY] The navigation bar should have a fixed position (i.e. it sticks to the top part of the screen).
- [x] [MANDATORY] The footer should have a fixed position (i.e. it sticks to the bottom part of the screen).
- [x] [MANDATORY] The width of the image, caption and article text should be the same as seen on the original page.    

Original Page          |  Your Page
:-------------------------:|:-------------------------:
 ![Screen Shot 2020-07-17 at 10 25 54 PM](https://user-images.githubusercontent.com/18187039/87835389-828d0000-c87c-11ea-98c4-08df43d8e2cc.png)|![Screen Shot 2020-07-17 at 10 27 03 PM](https://user-images.githubusercontent.com/18187039/87835445-acdebd80-c87c-11ea-8e77-559df418cd82.png)


- [x] [MANDATORY] The text under the video is not placed right. Kindly fix this.

Original Page          |  Your Page
:-------------------------:|:-------------------------:
![Screen Shot 2020-07-17 at 10 22 09 PM](https://user-images.githubusercontent.com/18187039/87835213-fda1e680-c87b-11ea-99f6-df8a66f395e3.png)|  ![Screen Shot 2020-07-17 at 10 21 11 PM](https://user-images.githubusercontent.com/18187039/87835175-e6fb8f80-c87b-11ea-8762-657a476e3d73.png)

- [x] [MANDATORY] 'The More in Space and Astronomy' section is off. The title does not also show up. Kindly fix this.

Original Page          |  Your Page
:-------------------------:|:-------------------------:
 ![Screen Shot 2020-07-17 at 10 33 21 PM](https://user-images.githubusercontent.com/18187039/87835761-8c633300-c87d-11ea-95d0-3a11f54d0543.png)|![Screen Shot 2020-07-17 at 10 32 41 PM](https://user-images.githubusercontent.com/18187039/87835728-75244580-c87d-11ea-9ac7-c7f4a4daf31d.png)

- [x] [MANDATORY] The images in 'The Editor Picks' section are not aligned. Kindly fix this.

Original Page          |  Your Page
:-------------------------:|:-------------------------:
 ![Screen Shot 2020-07-17 at 10 37 39 PM](https://user-images.githubusercontent.com/18187039/87835993-262ae000-c87e-11ea-8624-900448258d9d.png)|![Screen Shot 2020-07-17 at 10 35 02 PM](https://user-images.githubusercontent.com/18187039/87835824-ccc2b100-c87d-11ea-9474-da9aea29825d.png)

2020-07-17 22:40 UTC, krys2fa commented on README.md
> +- 👤GitHub: https://github.com/jose-Abel
- [x] [MANDATORY] Your README.md file should always include a link to a live version of your project for easy access by reviewers, potential collaborators and recruiters. You can host your projects on Github pages, Githack or Netlify.

- [x] [OPTIONAL] You can make your README.md file look professional here by writing your handles in markdown like this:
```
Github: [Daniel Ufeli](https://github.com/danielufeli)
```

2020-07-20 19:43 UTC, jose-Abel commented on README.md
> +- 👤GitHub: https://github.com/jose-Abel
Hello, 
Thanks for the feedback! We address all the mistakes that you indicate to us and we believe the code is ready for another code review. Appreciate your feedback!

2020-07-20 20:00 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

#### The page looks awesome, the code clean and we are almost there. 

- [x] The footer does not have a fixed position

- [x]  The line in the top of the editor's pick is a bit off

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87980385-ecd6b800-caa9-11ea-9353-60cf9d32fb04.png) | ![image](https://user-images.githubusercontent.com/61479648/87980503-17c10c00-caaa-11ea-9951-a8aa9fdc9238.png) |

### Do these two things and submit for a new review.  The project looks really great.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-20 21:18 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

#### You just have a few linter errors now. Kindly fix that and submit again. Like I said before, the project looks really good and you implemented everything that was requested :clap: 

- [x] linter errors

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-20 21:37 UTC, expjazz approved these changes
## Status:  Project Approved :100: 

#### Good luck on the next projects!

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-20 21:46 UTC, merged